language: node_js
node_js: node
script: yarn lint
jobs:
  include:
    - stage: deploy
      if: branch = master AND type = push
      script:
        - yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        committer-from-gh: true
        keep-history: true
        local-dir: app/build
